### ISSUE TITLE
Widget - Pictures from another server not showing

### ISSUE THREAD

**Issue by halimmd** [norbusan/piwigopress#21]
Hi
I have tried to display pictures from the local server the widget works almost fine (wish there were a way to hide descriptions).  But when I try it on sites hosted by others (1 & 1 and hostgator) I get only the menu but not images.  I have tried all the  options on the setup, but none.

I am doing something wrong?

**Comment by norbusan** [comment]
Hmm, do you have the latest version? There have been some changes to make remote albums work. Initially this was blocked by cross-site scripting, but here on my servers I can access remote albums.

Can you send me the link to a remote site that does not work for you?

Thanks

**Comment by halimmd** [comment]
Hi

 

Thanks for your prompt reply,  I have seen your post on the changes you have made but unfortunately it does not work for me. As far as updates, I stared with the current version  Wordpress.org (tried all the options) then I deleted it and installed the version on GitHub. The links are : my site is www.lesprintemps.com and the photos are on http://galerie.lesprintemps.com/ and http://gallery.hbfc.com/.

 

Thanks again

**Comment by norbusan** [comment]
Ok, I see what is going on. The sites you mention do *not* provide thumbnails, only square, small, etc sizes of photos.

I will try to fix that in a way that either thumbnail or square is used.

Thanks for the links, that helped a lot.

**Comment by halimmd** [comment]
Is it because I using ‘physical’ albums (because of ease of ftp)  instead on virtual ones?  In that case how can I make the system generate thumbnails? And what do you think I should do next?

 

Thanks

Halim

**Comment by norbusan** [comment]
Fixed in git, will be in the next release

**Comment by halimmd** [comment]
Hi, Its me again

 

I downloaded the zip copy from git, use it, but still having the same issue.  Sorry!!

**Comment by halimmd** [comment]
PS.

 

The options got messed-up a little. Besides the look, the ‘select all’ option does not work.

**Comment by norbusan** [comment]
Can you please be a bit more specific and provide screen shots? Which option? Where? In which screen?

It is working here on my system, so you need to show me what is going on!

Thanks

**Comment by halimmd** [comment]
I am using Wordpress  4.3


As far as the layout it does not bother me, but I don’t think you want it that way,

The ‘select all ’ checkbox has no effect. 

I tried with piwigo demo it does not work either.

 

Its 2am for me now (Morocco), I will be going to sleep soon, so I may not answer future messages immediately. Just send me an update please….

 

By the way you guys are doing a great job with piwigo and all.

 

Thanks a lot for your help.  

halim

**Comment by norbusan** [comment]
First of all, please when you answer by email, remove the quoted text, as it pollutes the web view. Please see: https://github.com/norbusan/piwigopress/issues/21 with all your longer and longer emails there.

Then:
* the "select all" does work, press it on and all options below are activated. Press it again and all options below are disabled.
* What is messed up in the layout? It has changed, that is on purpose to balance the columns, that's all. If anything else is messed up, screenshot please.

Thanks

**Comment by norbusan** [comment]
I have pushed another fix so that the descending order actually works.
